# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='doneAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
